abrignoni/ALEAPP

- README.md
- requirements.txt
Adds a requirements.txt for pip installing dependencies, and a couple of lines on the readme for instructions.
> Adds requirements

- scripts/artifacts/recentactivity.py
- scripts/artifacts/usagestats.py
- scripts/artifacts/wellbeing.py
- scripts/ilap_artifacts.py
- scripts/search_files.py
Zip works again now!
Changed regex for wellbeing
Now handles activities and usage stats for more than one user (if present)
> bug fixes + improvement

- aleapp.py
- scripts/artifact_report.py
- scripts/artifacts/installedappsGass.py
- scripts/artifacts/installedappsLibrary.py
- scripts/artifacts/installedappsVending.py
- scripts/artifacts/recentactivity.py
- scripts/artifacts/usagestats.py
- scripts/artifacts/wellbeing.py
- scripts/artifacts/wellbeingaccount.py
- scripts/ilap_artifacts.py
- scripts/search_files.py
+ Added ArtifactHtmlReport class to generate html content, so parsers don't need to know html.
+ Display processing time as HH:MM:SS
+ some other minor changes
> Add HTML writer module

- scripts/artifact_report.py
- scripts/artifacts/installedappsVending.py
Now parsers don't necessarily need to worry about the input they pass to write_artifact_data_table.
> + string conversion to write_artifact_data_table

- aleapp.py
- scripts/artifact_report.py
- scripts/artifacts/accounts_ce.py
- scripts/artifacts/accounts_ce_authtokens.py
- scripts/artifacts/accounts_de.py
- scripts/artifacts/calllog.py
- scripts/artifacts/cmh.py
- scripts/artifacts/installedappsGass.py
- scripts/artifacts/installedappsLibrary.py
- scripts/artifacts/installedappsVending.py
- scripts/artifacts/recentactivity.py
- scripts/artifacts/smsmms.py
- scripts/artifacts/usagestats.py
- scripts/artifacts/wellbeing.py
- scripts/artifacts/wellbeingaccount.py
- scripts/ilap_artifacts.py
- scripts/search_files.py
- Filter data_list for 'None' types are replace with blanks
- Implemented abstraction for search and with that removed redundant code from aleapp.py 
- Now passing search object as a parameter to each artifact parser - This is needed if the artifact parses a file/database that references another path, and it then needs to go look for it and parse/copy it. The mms parser needed this, and so will some other ones.
> Many changes

- scripts/artifacts/recentactivity.py
> Fixed slash issue with recentactivity artifact

- aleappGUI.py
- scripts/artifacts/smsmms.py
- scripts/dashboard.css
- scripts/ilap_artifacts.py
- scripts/report.py
Minor cleanup in some files too.
> SMS MMS parsers added

- aleappGUI.py
- scripts/artifacts/calllog.py
> Adding icons to call types

- scripts/artifacts/chrome.py
- scripts/ilap_artifacts.py
- scripts/report.py
Chrome browser history artifact + report icon
> Chrome browser history

- scripts/artifacts/chromeBookmarks.py
- scripts/artifacts/chromeLoginData.py
- scripts/ilap_artifacts.py
- scripts/report.py
Chrome bookmarks and login data artifacts
> More chrome artifacts

- scripts/artifacts/chromeCookies.py
- scripts/ilap_artifacts.py
Added Chrome browser cookies support
> Chrome cookies

- scripts/artifacts/chromeTopSites.py
- scripts/ilap_artifacts.py
- scripts/report.py
Added Chrome browser Top Sites support
> Chrome browser top sites

- aleappGUI.py
- scripts/artifacts/googlequicksearchbox.py
- scripts/blackboxprotobuf/License.blackboxprotobuf.txt
- scripts/blackboxprotobuf/__init__.py
- scripts/blackboxprotobuf/lib/__init__.py
- scripts/blackboxprotobuf/lib/interface.py
- scripts/blackboxprotobuf/lib/types/__init__.py
- scripts/blackboxprotobuf/lib/types/fixed.py
- scripts/blackboxprotobuf/lib/types/length_delim.py
- scripts/blackboxprotobuf/lib/types/type_maps.py
- scripts/blackboxprotobuf/lib/types/varint.py
- scripts/ilap_artifacts.py
- scripts/report.py
I'm including some protobuf parsing code from [blackboxprotobuf](https://github.com/nccgroup/blackboxprotobuf). This is a better (more complete) implementation for raw protobuf parsing and has more features than the one currently used in some other artifacts.
Also reduced the gui size for aleapp, as it needs to run on smaller screens. A lot of people run their tools in a VM with smaller screens.
> Adding google quick search and now parser

- scripts/artifacts/googleMusic.py
- scripts/ilap_artifacts.py
- scripts/report.py
Parses Google Music history. SQLite DB has a protobuf field. Could be parsed more efficiently with the newer protobuf implementation. Currently writing blobs out from DB to disk to then parse. Makes me sad.
> Google music

- scripts/artifacts/wifiProfiles.py
- scripts/ilap_artifacts.py
- scripts/report.py
Added support for Wi-Fi Profiles.
XML parsing.
> Wi fi profiles

- scripts/artifacts/sbrowser.py
- scripts/artifacts/sbrowserBookmarks.py
- scripts/artifacts/sbrowserCookies.py
- scripts/artifacts/sbrowserDownloads.py
- scripts/artifacts/sbrowserLoginData.py
- scripts/artifacts/sbrowserSearchTerms.py
- scripts/artifacts/sbrowserTopSites.py
- scripts/ilap_artifacts.py
- scripts/report.py
Android Browser History, Downloads, Top Sites. Bookmarks, Cookies, Search Terms, Login Data
> Android browser artifacts

- scripts/artifacts/chromeWebsearch.py
- scripts/artifacts/sbrowserWebsearch.py
- scripts/ilap_artifacts.py
- scripts/report.py
Added search terms parsing directly from the URLs since some (or all) are missed from the keyword search terms table in the history database.
> Web browser parsed search queries

- scripts/artifacts/build.py
- scripts/artifacts/siminfo.py
- scripts/ilap_artifacts.py
- scripts/report.py
Device info parsing for IMSI, phone number, build info, OS version, brand, etc...
> Device info

- scripts/artifacts/wifiProfiles.py
- scripts/ilap_artifacts.py
Hello. I've added database creation for WiFiProfile and also added  WiFiProfiles script to the "search" list in ilap_artifacts.
Please review.
> WiFi Profiles

- scripts/artifacts/usageapps.py
- scripts/ilap_artifacts.py
- scripts/report.py
Added support for Usage Apps as recorded in com.google.android.as/databases/reflection_gel_events.db
> Usage apps

- scripts/artifacts/journalStrings.py
- scripts/artifacts/walStrings.py
- scripts/ilap_artifacts.py
- scripts/report.py
Scripts to triage wal and journal files from SQLite databases by extracting ascii and unicode characters.
> Sq lite journaling strings

- scripts/artifacts/scontextLog.py
- scripts/artifacts/smanagerCrash.py
- scripts/artifacts/smanagerLow.py
- scripts/artifacts/smembersAppInv.py
- scripts/artifacts/smembersEvents.py
- scripts/artifacts/smyfilesRecents.py
- scripts/artifacts/smyfilesStored.py
- scripts/artifacts/usageapps.py
- scripts/ilap_artifacts.py
- scripts/report.py
Support for app interaction artifacts in:
- Samsung Myfiles.db
- Samsung Members
- Samsung Smart Manager
- Samsung Context Log
> Samsung app interaction

- aleapp.py
- aleappGUI.py
- scripts/ilapfuncs.py
There are now 2 buttons to browse folder or file. Selecting the input type dynamically enables/disables them. 
While at it, I also added a progress bar. Enjoy!
> GUI magic - Single input path + Progress bar

- scripts/artifacts/zyngachessChats.py
- scripts/ilap_artifacts.py
- scripts/report.py
I am new to this, so if this is wrong I apologize.  Also want to make sure that Jessica Hyde (@B1N2H3X) gets appropriate credit for the SQL Queries that were taken from her Artifact Exchange .xml.
> Zynga Chess Chat 

- aleapp.py
- aleappGUI.py
Second attempt :) Should work now. Please let me know if it doesnt.
> GUI changes with option to select which module to run

- aleappGUI.py
- scripts/report.py
Fixed bugs, removed getcwd() in 2 places.
Some code cleanup.
Went back to buttons on right side, as an editable text box is needed for user typed paths.
> Fix gui bug

- scripts/artifacts/emulatedSmeta.py
- scripts/ilap_artifacts.py
- scripts/report.py
Artifacts that parse the contents of the external.db sqlite data store.
> Metadata for files in emulated storage

- scripts/ilapfuncs.py
Function to generate KML files for geolocation coordinates.
> KML Support

- requirements.txt
- scripts/artifact_report.py
- scripts/artifacts/appicons.py
- scripts/artifacts/chromeLoginData.py
- scripts/artifacts/googleQuickSearchbox.py
- scripts/artifacts/googleQuickSearchboxRecent.py
- scripts/artifacts/packageInfo.py
- scripts/artifacts/recentactivity.py
- scripts/artifacts/settingsSecure.py
- scripts/artifacts/smsmms.py
- scripts/artifacts/wifiProfiles.py
- scripts/ilap_artifacts.py
Many minor changes, some cosmetic, others are bug fixes or regex enhancements for Android 11.
2 new plugins
Fix few bugs with some plugins and minor changes for Android 11 compatibility
> Some bug fixes, add support for Android 11, 2 plugins and more small changes

- aleapp.py
- aleappGUI.py
- scripts/artifact_report.py
- scripts/artifacts/ADB_Hosts.py
- scripts/artifacts/etc_hosts.py
- scripts/ilap_artifacts.py
Adds support for file paths > 260 char on windows.
Old adb_hosts is now etc_hosts
New adb_hosts plugin
> long path fix, new adb_hosts, old is now etc_hosts

- scripts/artifacts/cmh.py
- scripts/ilapfuncs.py
Added field to query to include originating application (bucket.)
Created geolocation mapping output for entries with GPS data points.
> Samsung CMH

- scripts/artifacts/smyFiles.py
- scripts/ilap_artifacts.py
> Updated MyFiles.db parsing

- requirements.txt
- scripts/artifacts/Cello.py
- scripts/artifacts/ChessWithFriends.py
- scripts/artifacts/DocList.py
- scripts/artifacts/WordsWithFriends.py
- scripts/ilap_artifacts.py
- scripts/version_info.py
Added missing requirement (simplekml) too.
> Offline Google docs extraction + minor cleanup

- scripts/search_files.py
> fix search regex inconsistency - dir vs tar/zip

- scripts/artifacts/Viber.py
- scripts/artifacts/Xender.py
- scripts/artifacts/Zapya.py
- scripts/ilap_artifacts.py
Add support for data from Viber, Xender and Zapya Applications.
> Add support for Viber, Xender and Zapya Applications

- scripts/artifacts/lgRCS.py
- scripts/ilap_artifacts.py
- scripts/report.py
Chats to include location on the device of sent and received files
> RCS Chats for LG Phones

- scripts/artifacts/gboard.py
- scripts/version_info.py
Add parsing of trainingcachev2.db
> Add read_trainingcachev2()

- scripts/artifacts/Cast.py
- scripts/ilap_artifacts.py
- scripts/report.py
> Add Cast parser

- scripts/artifacts/etc_hosts.py
- scripts/dark-mode.css
- scripts/report.py
Reducing the clutter (by removing default entries). Default entries are:
127.0.0.1 - localhost
::1 - localhostipv6
Output will be there only if there is anything else seen.
> Add icon for etc-hosts + dont show if default

- README.md
- aleapp.py
- aleappGUI.py
- scripts/artifacts/lgRCS.py
- scripts/ilap_artifacts.py
- scripts/search_files.py
- scripts/version_info.py
- Added changes that were in iLeapp for various bugs/issues/improvements here.
- Added gz support
- Fixed lg_RCS exception
- aleapp.py options are now case-insensitive ( "-t Fs"  would work now, prev only "-f fs" worked)
- Readme updated too
> .gz support and some misc minor updates

- scripts/artifacts/runtimePerms.py
- scripts/ilap_artifacts.py
- scripts/report.py
Compatible with Android 10 & 11.
List of app permissions as accepted per the user.
> Runtime permissions per app

- scripts/artifacts/Viber.py
- Fixed date formats to now be parsed from Unix Epoch
- Added timestamps to the front of the queries for timelining fix
- General formatting fixes for report viewing
> Minor Viber timestamp and formatting fixes

- scripts/artifacts/permissions.py
- scripts/ilap_artifacts.py
- scripts/report.py
Android permissions
Parser for the permissions.xml file.
Parses for the following:
- Permission trees
- Android permissions
- Package, shared user, updated package permissions
> Android permissions

- .gitignore
- scripts/artifacts/packageGplinks.py
- scripts/ilap_artifacts.py
Will generate the Google Play link for the installed app.
Not all links will have a corresponding Google Play page since first party apps are only obtained via the device and not via Google Play.
> Package Google Play Link

- scripts/artifacts/fitbitExercise.py
- scripts/ilap_artifacts.py
- scripts/report.py
Fitbit exercise artifact with geolocation
-Generates KMLs per session
> Fitbit artifact - Exercise

- scripts/artifacts/fitbitActivity.py
- scripts/artifacts/fitbitExercise.py
- scripts/artifacts/fitbitHeart.py
- scripts/artifacts/fitbitSleep.py
- scripts/artifacts/fitbitSocial.py
- scripts/artifacts/fitbitWalk.py
- scripts/ilap_artifacts.py
- scripts/version_info.py
Parsers for heart, sleep, walking, social, and activities.
> Fitbit artifacts

- requirements.txt
> Add packaging module

- scripts/artifacts/googleKeepNotes.py
- scripts/artifacts/googleKeepNotesSharing.py
- scripts/ilap_artifacts.py
This should fix the notes sharing email id and timestamp.
> Fix Notes shared email

- scripts/artifacts/Whatsapp.py
- scripts/ilap_artifacts.py
Added ability to retrieve the Whatsapp version, User Name, User status, Country Code, and Mobile Number.
Adding screenshot for reference:
> Update whatsapp.py to retrieve user's profile

- scripts/artifacts/chromeAutofill.py
- scripts/version_info.py
- Add Autofill - Profiles to the parser
- Rebrand past Autofill to Autofill - Entries
- Bump the version number
> Update Autofill Parser

- scripts/artifacts/googleNowPlaying.py
- scripts/ilap_artifacts.py
- Adds the Android 11 location path for Google Now Playing
> Update 'Now Playing' path

- scripts/artifacts/Turbo.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
- Updates to Battery (Turbo) parser
- Parses bluetooth device battery info
> Add Turbo - Bluetooth Device info

- scripts/artifacts/Turbo_AppUsage.py
- scripts/artifacts/Turbo_Battery.py
- scripts/artifacts/bluetoothConnections.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
- Change Turbo naming to "Device Health Services"
- Add Application Usage from Turbo
- minor changes to Bluetooth Connections
> Turbo & Bluetooth Updates 

- scripts/artifacts/appopSetupWiz.py
- scripts/artifacts/appops.py
- scripts/artifacts/setupWizardinfo.py
- scripts/artifacts/suggestions.py
- scripts/ilap_artifacts.py
- scripts/report.py
Artifacts indicate when a device was wiped
> Wipe and restore artifacts

- scripts/artifacts/sRecoveryhist.py
- scripts/artifacts/sWipehist.py
- scripts/ilap_artifacts.py
- scripts/report.py
When the device was wiped with timestamps.
> Samsung Wipe & Recovery History

- scripts/artifacts/errp.py
- scripts/ilap_artifacts.py
> Samsung eRR.p

- scripts/artifacts/kikReturns.py
- scripts/ilap_artifacts.py
> Kik Warrant Returns

- scripts/artifacts/googleTasks.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
Added Google Tasks ability. It can retrieve creation, modification, completion timestamp, due date, Task, list, recurrence ID, Task Name, and details.
There is some python issue while retrieving the whole timestamp for the due date, but it is added to the script, once the issue is fixed, will send a new pull request.
Test data can be found here: http://transfer.sh/1ODDxn5/tasks.zip.
> Adding new artifact - Google Tasks

- scripts/artifacts/chromeAutofill.py
- scripts/artifacts/installedappsVending.py
Fixes some versioning errors with missing columns
> Update InstalledApps and Chrome Autofill

- scripts/artifacts/gmail.py
- scripts/ilap_artifacts.py
First commit for active gmail artifact. Returns a single gmail address, if available. Added under category "gmail". Tested on android 11.
> Parse active gmail account information

- scripts/artifacts/googlemapaudio.py
- scripts/ilap_artifacts.py
Hi Briggs,
Please consider this PR for ALEAPP...
I've written a short blog post explaining the artefact - hopefully this helps?
https://kibaffo33.data.blog/2021/12/30/at-the-roundabout-take-the-second-exit/
Thanks
Bob
> Google Maps Voice Guidance

- scripts/artifacts/appopSetupWiz.py
- scripts/artifacts/appops.py
- scripts/artifacts/packageInfo.py
- scripts/artifacts/permissions.py
- scripts/artifacts/recentactivity.py
- scripts/artifacts/settingsSecure.py
- scripts/ilap_artifacts.py
- scripts/ilapfuncs.py
- scripts/report.py
Updated artifacts that parse XML to also support binary XML (ABX format).
> ABX support added

- scripts/artifacts/clipBoard.py
- scripts/ilap_artifacts.py
- scripts/ilapfuncs.py
- scripts/report.py
- scripts/search_files.py
Clipboard triage report
Added modified time to files extracted from zip.
> Clipboard Data

- scripts/artifacts/googleTasks.py
- scripts/artifacts/shutdown_checkpoints.py
- scripts/artifacts/waze.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
- parses Waze recently searched locations
- parses shutdown checkpoint info and timestamps
> Waze & Shutdown Checkpoints

- scripts/artifacts/firefox.py
- scripts/artifacts/firefoxCookies.py
- scripts/ilap_artifacts.py
- scripts/report.py
- Change Visits and History to separate categories
- Add Bookmarks
> Firefox Updates

- scripts/artifacts/playgroundVault.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
App locker decryption courtesy of incidentalchewtoy:
https://theincidentalchewtoy.wordpress.com/2021/12/12/decrypting-apps-lock-file-encryption-gold-version/
> Playground app locker

- scripts/artifacts/appLockerfishingnet.py
- scripts/artifacts/discreteNative.py
- scripts/artifacts/playgroundVault.py
- scripts/ilapfuncs.py
> Changes to app locker

- scripts/artifacts/discreteNative.py
- scripts/ilap_artifacts.py
- scripts/report.py
> Privacy Dashboard parser

- scripts/artifacts/protonmailContacts.py
- scripts/artifacts/protonmailMessages.py
- scripts/ilap_artifacts.py
- scripts/report.py
> ProtonMail Metadata

- scripts/artifacts/googleMessages.py
- scripts/ilap_artifacts.py
- scripts/report.py
Adds functionality to parse Google Messages app.
> Added Google Messages

- scripts/artifacts/googleChat.py
- scripts/artifacts/googleFitGMS.py
- scripts/ilap_artifacts.py
- scripts/report.py
Add ability to parse Google Chat and Google Fit (GMS) data.
> Add Google Chat and Google Fit

- scripts/artifacts/burner.py
- scripts/artifacts/groupMe.py
- scripts/ilap_artifacts.py
- scripts/report.py
Add functionality to parse GroupMe group and message information.  Also update column header in Burner script.
> Add GroupMe and update to Burner

- scripts/artifacts/vaulty_files.py
- scripts/artifacts/vaulty_info.py
- scripts/ilap_artifacts.py
Hi Brigs,
Incoming Artefact! 
Vaulty - `com.theronrogers.vaultyfree`
Proof of work: https://kibaffo33.data.blog/2022/03/05/decoding-vaulty/
Hopefully this is ok!
Thank you
> Adds Vaulty

- scripts/artifacts/imagemngCache.py
- scripts/ilap_artifacts.py
- scripts/report.py
Media from all apps.
Can include deleted media.
> Image Disk Manager Cache

- scripts/artifacts/googleKeepNotes.py
- scripts/artifacts/slopes.py
- scripts/ilap_artifacts.py
- scripts/report.py
Keep Notes
- add check for -wal
Slopes
- resort details
- activity
- lift details
> Fix Keep Notes / Add Slopes parser

- scripts/artifacts/kijijiConversations.py
- scripts/artifacts/kijijiLocalUserInfo.py
- Kijiji Local User Info - Minor update to include local user information when logged-out of the application.
- Kijiji Conversations - Update to include the Conversation ID (thread ID) within the report.
> Kijiji local user + conversation enhancements

- scripts/artifacts/duckThumbs.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
> DuckDuckGo Tab Thumbnails

- scripts/artifacts/Whatsapp.py
- scripts/ilap_artifacts.py
- scripts/report.py
- Takes into account for new column names
- Will parse old and new versions now
> WhatsApp Updates

- scripts/artifacts/Whatsapp.py
- scripts/ilap_artifacts.py
Added attachment display support.
> WhatsApp Update

- scripts/artifacts/smyfilescache.py
- scripts/ilap_artifacts.py
- scripts/report.py
- scripts/version_info.py
Correlate thumbs & media metadata from the Samsung My Files app.
> My Files cache media

- aleapp.py
First set of updated artifacts
> Updated artifacts

- scripts/artifacts/usageHistory.py
Support for old usagestats format.
> Updated Artifact

- aleappGUI.py
- scripts/artifacts/usagestatsVersion.py
This PR introduces profiles to ALEAPP. 
Profiles are simple JSON files which contain a list of plugins to execute, allowing users to pre-define a set of artefacts to run for different scenarios. 
(This PR also fixes the name of the usagestatsversion plugin)
> Add save-able/load-able processing profiles.

- README.md
- aleappGUI.py
Fix a crashing bug with destination_path type checking ( like #282 )
Fix markdown formatting for readme, plus typo causing incorrect syntax detection.
> GUI bug and MD formatting

- scripts/artifacts/protonVPN.py
- scripts/report.py
Artifacts Location : /data/data/ch.protonvpn.android/
> Added ProtonVPN Artifacts

- scripts/artifacts/bumble.py
- scripts/report.py
- Parses chats
- Matches
- User profile settings
> Bumble Parser

- scripts/artifacts/mastodon.py
- scripts/artifacts/tusky.py
- scripts/report.py
- scripts/version_info.py
Tusky
- account details
- timeline details
Mastodon
- adds attachment URLs
> Tusky Parser & Mastodon updates

- scripts/artifacts/SimpleStorage_applaunch.py
- scripts/report.py
Much thanks to @joshuahickman1
> SimpleStorage - App Launch

- scripts/artifacts/googleMapsGmm.py
- scripts/report.py
Pulls out GPS coordinates (to & from) for Google maps searches to include the google maps URL.
> gmm_storage.db parsing

- scripts/artifacts/downloads.py
- scripts/report.py
Downloads
- pulls details on downloads from the native system, including timestamps, urls, file names/sizes, etc.
Report
- also alphabetized the report script
> Downloads parser

- scripts/artifacts/WhatsApp.py
- scripts/artifacts/downloads.py
- scripts/artifacts/mewe.py
- scripts/artifacts/snapchat.py
- Small fixes to display proper times in timeline
- Remove entries that aren't timestamps
> Timelining Updates

- scripts/artifacts/downloads.py
- scripts/artifacts/fitbitDevices.py
- scripts/artifacts/garmin.py
- scripts/artifacts/slopes.py
- scripts/report.py
- Cache DB activities
- GCM cache activities
- Device / device connections
- device notifications
- sleep activities
- weather
> Garmin Parser + small updates

- scripts/artifacts/sWipehist.py
- scripts/report.py
Added recovery_history.log to the parser. Added provider data to the wipe events.
> Update Samsung Wipe History Log

- scripts/artifacts/smyFiles2.py
- scripts/artifacts/smyfilesRecents.py
- scripts/artifacts/smyfilesStored.py
Update to the Samsung My Files app.
> Samsung MyFiles Updates

- scripts/artifacts/smyFiles2.py
- scripts/artifacts/smyfilesStored.py
Added queries for other versions
> Update to MyFiles

- scripts/artifacts/offlinePages.py
- scripts/report.py
Find .mht & .mhtml files and extract mime metadata and link to file in the report.
> Offline pages parser

- scripts/artifacts/browserCachechrome.py
- scripts/report.py
Get source URL, modified time, and unzipped file content from the Chrome cache parser.
> Android Chrome browser cache files parser

- scripts/artifacts/FacebookMessenger.py
- scripts/report.py
- scripts/version_info.py
- Adds support for msys_database format
> Facebook Messenger Update

- scripts/ilapfuncs.py
- scripts/version_info.py
Links to media in the report now use targer = blank
> Misc updates

- aleapp.py
- aleappGUI.py
- scripts/report.py
Add case data to the case information section in the HTML report. The case data is a simple dictionary not nested. Single keys and single value per key.
> Case data added to HTML report

- scripts/artifacts/hikvision.py
- scripts/report.py
Hikvision is a well-known app that is used to remotely access/operate CCTV systems. Currently the following information can be interpreted:
-Hikvision - CCTV Channels: retrieves info for the available CCTV record channels
-Hikvision - CCTV Info: Information about the CCTV system
-Hikvision - CCTV Activity: User Interaction with the app. Unfortunately it is not easy to attribute user actions but indirectly can indicate remote live view/play back from CCTV footage.
-Hikvision - User Created Media:
The media files the user created while viewing footage from the CCTV
> Introducing Hikvision App's Parser

- requirements.txt
- scripts/artifacts/StravaGPS.py
- scripts/report.py
Great Discovery!
It is no surprise that Strava is probably the most popular Social Fitness App in the Play Store since it works with almost all companion Apps.
Strava was exploited in the past, for example, the famous breach that made it possible to expose Israeli military bases [article](https://www.forbes.com/sites/abrambrown/2022/06/20/strava-fitness-app-israeli-mossad-data-breach-security-hack-segments/?sh=64979a7468d7).  Since then Strava is much more fortified and the application stores almost no type of data locally. The application, the moment it has access to the internet, purges the data automatically from the local SQLite Databases.
However, exploring the data, we discovered that the application stores FIT files related to the activities in the Public directory! A FIT or …
> Strava Artifact

- scripts/artifacts/pikpakCloudlist.py
- scripts/report.py
Files from PikPak cloud. Thumbnail links are clickable. May fetch the thumbnail if clicked on.
> PikPak cloud list

- scripts/artifacts/pikpakDownloads.py
- scripts/artifacts/pikpakPlay.py
PIkpak downloads and play history
> PikPak artifacts

- scripts/artifacts/AdidasActivities.py
- scripts/artifacts/AdidasUser.py
- scripts/artifacts/MMWActivities.py
- scripts/artifacts/MMWUsers.py
- scripts/artifacts/NikeNotifications.py
- scripts/artifacts/PumaActivities.py
- scripts/artifacts/PumaUsers.py
- scripts/artifacts/RunkeeperActivities.py
- scripts/artifacts/RunkeeperUser.py
- scripts/artifacts/StravaGPS.py
- scripts/report.py
We are creating a study to compare commercial fitness applications that are related to fitness brands but are not associated with wearables (running applications).
We aim to find resemblances in the different apps to create a uniform method of studying any of these types of applications. 
For this, we created artifacts that extract activities and user information from the following applications:
[Adidas Running](https://play.google.com/store/apps/details?id=com.runtastic.android)
[Pumatrac](https://play.google.com/store/apps/details?id=com.pumapumatrac)
[Map My Walk](https://play.google.com/store/apps/details?id=com.mapmywalk.android2)
[RunKeeper](https://play.google.com/store/apps/details?id=com.fitnesskeeper.runkeeper.pro)
They complement the already done Nike Run Club and Strava …
> Added Various Fitness Artifacts

- requirements.txt
- scripts/artifacts/bittorrentClientpref.py
- scripts/artifacts/bittorrentDlhist.py
- scripts/artifacts/torrentResumeinfo.py
- scripts/artifacts/torrentinfo.py
- scripts/report.py
Bittorent client preferences
Download History
Torrent information
Torrent Resume info
> Torrent artifacts

- scripts/artifacts/torrentinfo.py
- scripts/artifacts/wifiConfigstore.py
made script recognize multiple wificonfig xml files and report accordingly.
> Wificonfig update

- scripts/artifacts/wifiConfigstore.py
- scripts/artifacts/wifiProfiles.py
- scripts/ilapfuncs.py
> Timestamp fix

- scripts/artifacts/rarlabPreferences.py
- scripts/report.py
Includes preference settings for com.rarlab.rar to include file history.
> com.rarlab.rar Preferences

- aleapp.py
This reverts commit 1261074602fda89af0cd69aa4076a726767760c9, reversing changes made to 61b0203c43bb1127169ccb41bdb62263f3c5cb55.
> Revert "Merge pull request #365 from Crane-Mocker/main"

- scripts/artifacts/galleryTrash.py
- scripts/report.py
Images sent to the trash with corresponding metadata.
> Andorid Gallery Trash

- scripts/artifacts/googlemapaudioTemp.py
- scripts/report.py
Media files for audio. Correlates to last trip taken.
> Google Voice Temp Audio Guidance

- scripts/artifacts/gboard.py
- scripts/report.py
- scripts/version_info.py
- Add clipboard parsing
- minor fixes
> Gboard Updates

- .gitignore
- aleappGUI.py
- requirements.txt
- scripts/artifacts/AdidasActivities.py
- scripts/artifacts/GarminPolyAPI.py
- scripts/artifacts/GarminPolyline.py
- scripts/artifacts/MMWActivities.py
- scripts/artifacts/NikePolyline.py
- scripts/artifacts/PumaActivities.py
- scripts/artifacts/RunkeeperActivities.py
- scripts/artifacts/StravaGPS.py
- scripts/ilapfuncs.py
Modification of Fitness modules related to GPS tracking of the apps:
- Adidas
- Garmin
- Nike
- Runkeeper
- Map My Walk
- Strava
- Puma
A new file is generated for each record, an XLSX file containing the coordinates, possibly the timestamp when the user was there, and the respective **road**, **city**, **postcode**, and **country**. This is archived using the Python dependencies **geopy** that returns this information from the coordinates.
To not overload this library and create a cache of information, the data is stored in a local SQLite3 database. In future generated reports, the users ALEAPP will get the data from the database instead of the library.
> Modification of GPS fitness artifacts

- scripts/artifacts/airtagAndroid.py
- scripts/report.py
Airtag alerts and scans artifact.
> Airtag detection support

- scripts/artifacts/libretorrent.py
- scripts/report.py
> Libre Torrent

- scripts/artifacts/libretorrent.py
- scripts/artifacts/libretorrentFR.py
Look for the database name only since it should be used by other apps.
> LIbre Torrents path expansion

- scripts/artifacts/discordChats.py
- scripts/report.py
Discord chat are in json from a sqlite database.
> Discord Chats

- scripts/artifacts/airGuard.py
- scripts/artifacts/chromeBookmarks.py
- scripts/artifacts/chromeDIPS.py
- scripts/artifacts/imagemngCache.py
- scripts/artifacts/oldpowerOffReset.py
- scripts/artifacts/shutdown_checkpoints.py
Updates to parsers to handle different versions:
- AirGuard
- Chrome Bookmarks
- Image Manager Cache
- Power Off Reset
- Shutdown Checkpoints
> Versioning Fixes

- scripts/artifacts/googleMapsSearches.py
- scripts/ilapfuncs.py
> Google Maps Searches

- scripts/artifacts/fitbit.py
- scripts/report.py
- Consolidates from 7 parsers down to 1 single checkbox
- Multiprofile support with source columns
- Artifact_v2 added
> Fitbit Consolidation & Multiprofile Support

- README.md
- aleapp.py
- aleappGUI.py
- scripts/report.py
- Added ALEAPP profile file loading and profile file creation in the CLI
- Removed unused imports
- References to iLEAPP or iOS were replaced with ALEAPP and Android
- Removed lastbuild parser with usagestatsVersion
- Fixed usagestatsVersion parser was not executed first in the CLI
> Added profile files in the CLI

- scripts/artifacts/googleMapsGmm.py
- Adding GMM_MyPlaces.db Parsing for the Label place in google maps. 
- Refactor of the original code to be able to include the gmm_myplaces.db with gmm_storage.db parsing
> Adding GMM_MyPlaces.db Parsing

- aleapp.py
- aleappGUI.py
- scripts/report.py
- zCaseDataExample.alprofile
- zCaseDataExample.lcasedata
- zProfileExample.alprofile
'Load Case Data' button was replaced with a 'Add Case Data' button in the GUI.
In the CLI:
- '-m' is used to load an ALEAPP profile file (.alprofile)
- '-d' is used to load a LEAPP case data file
- -'c' is used to create an ALEAPP profile file and/or a LEAPP case data file
Two example files (zCaseDataExample.lcasedata & zProfileExample.alprofile) are available at the root or the repo.
> Add Case Data management

- scripts/artifacts/teleguard.py
- scripts/report.py
Added Teleguard messaging support.
> Teleguard Messaging

- scripts/artifacts/teleguard.py
- scripts/report.py
Added Contacts, Posts, & Channels support.
> Teleguard update

- scripts/artifacts/Life360.py
- scripts/report.py
- scripts/version_info.py
- Life360 cached locations
- Life360 device battery
- Life360 places (favorites)
- removed duplicate entry for Alex as contributor
> Life360 Parser

- scripts/artifacts/Life360.py
- Allow for timezone offsetting
> Fix Life360 Timestamps

- scripts/artifacts/gmailEmails.py
Support multiple Gmail database processing. Closes issue #454
> Support multiple Gmail database processing

- scripts/artifacts/FCMQueuedMessagesDump.py
- scripts/artifacts/chrome.py
- scripts/artifacts/chromeAutofill.py
- scripts/artifacts/chromeBookmarks.py
- scripts/artifacts/chromeCookies.py
- scripts/artifacts/chromeDIPS.py
- scripts/artifacts/chromeLoginData.py
- scripts/artifacts/chromeMediaHistory.py
- scripts/artifacts/chromeNetworkActionPredictor.py
- scripts/artifacts/chromeOfflinePages.py
- scripts/artifacts/chromeTopSites.py
Accepts 'c' as an alias to instagram data key 'collapse_key'. Closes #459
Support chrome webview artifacts.
> Solves #459 and #461

- scripts/artifacts/googleLastTrip.py
Populates place information from fields 1 or 4. Not all artifacts has field 4 populated, what was causing exception to be thrown, described in issue #462.
> Populates place information from fields 1 or 4 in Google Last Trip

- scripts/artifacts/chromeAutofill.py
- scripts/artifacts/chromeBookmarks.py
- scripts/artifacts/chromeCookies.py
- scripts/artifacts/chromeDIPS.py
- scripts/artifacts/chromeLoginData.py
- scripts/artifacts/chromeMediaHistory.py
- scripts/artifacts/chromeNetworkActionPredictor.py
- scripts/artifacts/chromeOfflinePages.py
- scripts/artifacts/chromeTopSites.py
Hi, @abrignoni .
Last PR #460 has import statement errors.
I call ALeapp from a processing/indexing engine (https://github.com/sepinf-inc/IPED) that solves these imports so I have not detected the error in ALeapp standalone execution.
These PR corrects this.
Sorry.
> Solves Import reference error in last PR #460

- scripts/artifacts/sChats.py
Parses the chat application Sideline.
> New Android Sideline App Parser

- scripts/artifacts/burnerContacts.py
- scripts/artifacts/burnerMessages.py
- scripts/artifacts/burnerSubscription.py
- scripts/artifacts/burnerUser.py
Burner support for contacts, messages, subscription, and user.
> Burner Parser

- scripts/version_info.py
> add me to contributors

- scripts/artifacts/WithingsHealthMate.py
New Artifacts are:
- Accounts
- Trackings
- Locations
- Messages
- Contacts
- Measurements
- Devices
> Added new Artifacts for Withings HealthMate App

- scripts/artifacts/wireMessenger.py
I have added initial support for Wire Messenger in ALEAPP, it still needs some extra work to embed the media files into the content of the message and to grab the protobuf containing the location data.
> wireMessenger.py

- scripts/artifacts/K9Mail.py
- scripts/artifacts/WithingsHealthMate.py
- scripts/report.py
- scripts/version_info.py
- Refinement of Artifact Withings Health Mate App
- Added artifacts for App K-9 Mail (based on https://bebinary4n6.blogspot.com/2024/05/app-k-9-mail-for-android.html)
- Added Icons for Withings Health Mate App and K-9 Mail App artifacts
- Added myself to the list of contributers
> Added new artifact for App K-9 Mail and minor changes

- scripts/artifacts/MicrosoftAuthenticator.py
- scripts/artifacts/battery_usage_v9.py
- scripts/artifacts/wifiHotspot.py
- scripts/report.py
- Added Artifact for Acccounts that are configured in the Microsoft authenticator
- Added key "WifiSsid" to the wifihotspot.py - so this artifact also works with Android 14 (the key "SSID" changed from Android 13 to Android 14)
- And: two new Artifacts - Battery States and App Battery Usage Events on Android 14.  For more info see blogpost: https://bebinary4n6.blogspot.com/2024/05/android-14-battery-usage-and-app-usage.html
> Added artifact for MS authenticator and minor change to wifihotspot.py for Android 14 support

- scripts/artifacts/battery_usage_v9.py
- Added decoding of field batteryInfo (base64 / protobuf) from battery-usage-db-v9
- Removed, where possible, unnecessary decoding of field batteryInfoDebug from battery-usage-db-v9
> Changes on battery-usage-db-v9 for better support of different devices

- scripts/artifacts/likee.py
Capable of analyzing and identifying Likee users, direct message content, and device location. Working on additional capability. 
A note on location data
- The location data returned on several tests was within one-eighth of a mile from the site where the device activity was conducted to create the dataset.
> Likee Application Data Analysis

- scripts/artifacts/SamsungHoneyboard.py
- scripts/version_info.py
Adding
- Samsung honeyboard clipboard text parser for the ClipItem database
- Samsung honeyboard clipboard screenshot parser.
- Myself to the version_info
> Adding Samsung Honeyboard clipboard parser

- plugin_loader.py
- scripts/artifacts/appSemloc.py
- scripts/artifacts/ulrUserprefs.py
http://thebinaryhick.blog/2024/06/28/the-green-look-back-androids-on-device-location-history/
> Google on device Location History

- scripts/artifacts/sharedProto.py
SBrowser downloads as found in a leveldb data store.
> Share proto DB

- scripts/artifacts/calllog.py
Sorry for the second tiny PR, only just noticed this other small bug in the calllog.py code.
> fix error on calllog.py data appending

- scripts/artifacts/waze.py
> Wrong join in the Waze parser #519

- scripts/artifacts/gmailEmails.py
- Added null checks for email ID (row[7]) to avoid processing null values.
- Simplified and optimized logic for extracting 'to', 'toname', 'replyto', and 'replytoname' using get method with fallbacks.
- Fixed decoding for 'mailedby' and 'signedby' by handling cases where these fields might be missing or empty.
- Ensured proper handling of message HTML content by appending decoded message parts correctly.
- Retained functionality for generating reports, timelines, and TSV files for Gmail email data, label details, and download requests.
- Updated logic for attaching files, checking for 'noname' and empty values in attachment fields.
No major changes to the database querying logic or report generation. Code adjusted for better maintainability and clarity.
> refactor(gmailEmails.py): improve Gmail email parsing and decoding logic

- scripts/artifacts/blueskymessages.py
- scripts/artifacts/blueskyposts.py
Removed the grep for the testing directories.
> Removed Bluesky test directory grep

- scripts/artifacts/blueskymessages.py
- scripts/artifacts/blueskyposts.py
- scripts/ilapfuncs.py
> Bluesky support for emojis

- scripts/googleKeepNotes.py
To replace previously submitted keepNotes.py Adds capability for linking attachments to notes.
> Google Keep Notes Updated

- scripts/artifacts/WhatsApp.py
- scripts/version_info.py
Add the new QUERY
SELECT
datetime(chat_view.created_timestamp/1000,'unixepoch') AS "Group Creation Time",
chat_view.subject AS "Group Name",
( SELECT creator_jid FROM wadb.wa_group_admin_settings WHERE wadb.wa_group_admin_settings.jid = jid.raw_string) AS "Creator JID",
( SELECT wa_name FROM wadb.wa_contacts WHERE wadb.wa_contacts.jid = (SELECT creator_jid FROM wadb.wa_group_admin_settings WHERE wadb.wa_group_admin_settings.jid = jid.raw_string) ) AS "Creator WA User Name",
( SELECT number FROM wadb.wa_contacts WHERE wadb.wa_contacts.jid = (SELECT creator_jid FROM wadb.wa_group_admin_settings WHERE wadb.wa_group_admin_settings.jid = jid.raw_string) ) AS "Creator WA Number"
FROM
chat_view
JOIN jid ON jid._id = chat_view.jid_row_id
LEFT JOIN wa_group_admin_settings ON …
> Add new Query for Group Details

- scripts/artifacts/OneDrive_Metadata.py
- scripts/version_info.py
Created a OneDrive Metadata artifact based on Anthony Reince's inital work. 
- Artifact could use some work with opening thumbnails in a new tab, but the ability to right-click>> Open Image in New Tab works just fine.
Updated Version info with Anthony Reince info with his permission.
> OneDrive Metadata Artifact

- scripts/artifacts/LinkedIn.py
New parser for LinkedIn-App on Android .
> Added parser for LinkedIn (Account and Messages)

- scripts/artifacts/knuddels.py
This adds a new parser for chat messages from the Android app "Knuddels Chat". 
Messages are extracted directly from local database files, so no external packages are required.
"Knuddels Chat" refers to the chat system used on [Knuddels.de](https://www.knuddels.de/), a popular German online community and social networking platform.
> new parser for knuddels chat messenger

- scripts/artifacts/chatgpt2.py
update path to include the wal file for chatgpt parser
> Brigs working

- scripts/artifacts/androidauto.py
Extracts a list of connected cars from Android Auto - the connection time, manufacturer, model, year, Bluetooth and Wi-Fi connection details.
Sample data (from BelkaCTF №7) - [com.google.android.projection.gearhead.zip](https://github.com/user-attachments/files/21456216/com.google.android.projection.gearhead.zip)
Resulting report:
> Implement Android Auto extractor

- scripts/artifacts/last_boot_time.py
- scripts/artifacts/powerOffReset.py
- scripts/artifacts/shutdown_checkpoints.py
> Power Events LAVA Updates
