abrignoni/ALEAPP

- scripts/dark-mode.css
> CSS fix for pre html tag in dark mode

- .github/workflows/ALEAPP-BuildPipeline.yaml
Note for future builds - if any new dependencies are added for which there are no prebuilt binaries (wheels) available on pypi, this action will fail. However, I have a workaround which you will see in the incoming iLEAPP version of this PR to supplement when the wheels are unavailable.
I have run multiple test releases with this update and had no issues.
> Point CI/CD to new fork of pyinstaller-windows on python 3.9.2 / pyinstaller 4.2

- scripts/artifacts/chromeNetworkActionPredictor.py
- scripts/ilap_artifacts.py
- scripts/report.py
Network Action Predictor is a preloading feature Chrome uses to attempt and guess what webpages someone will click on when searching
> Add Chrome Network Action Predictor

- scripts/artifacts/googleKeep.py
- scripts/artifacts/googleKeepNotes.py
- scripts/ilap_artifacts.py
Added Google Keep - Notes ability. It will retrieve the notes text, created, updated timestamp, last modifier email, and parent id of the notes. 
To-do Artifacts in Google Keep:
Adding screenshots for reference:
> Add new artifact: Google Keep - Notes

- requirements.txt
wheel package required for a fresh install on Windows 11.
Specifically, simplekml and blackboxprotobuf require wheel.
> include wheel as a requirement

- requirements.txt
Relates to #178 
Hi Briggs, these requirements appear to be missing following the SGallery addition.
Still appears problematic though... 
- When I install the original `requirements.txt`, followed by the three additions, ALEAPP runs fine.
- When the three additions are inside `requirements.txt` and installed, ALEAPP still missing libraries...
Now I'm confused!
> Adds requirements for SGallery

- scripts/artifacts/NQVault.py
- scripts/ilap_artifacts.py
Brigs,
Script to decrypt "encrypted" PIN + Media in NQ Vault (com.netqin.ps).
_**How it works:**_
- Vault seems to support a minimum pin length of 3 and a maximum pin length of  15.
- PIN is hashed using the java hashcode method.
- Media is encrypted using XOR.
- PIN and encrypted media files are stored in this location:
- /storage/emulated/0/Android/data/com.netqin.ps/files/Documents/SystemAndroid/Data
- Database within the above location containing encrypted(hashedcode) PIN and media file info is: 322w465ay423xy11
It seems when you save an image/video into NQ vault, a new file path is created that follows this structure:
**/emulated/0/Android/data/com.netqin.ps/files/Documents/SystemAndroid/Data/[Base64 encoded value of PIN in hashcode)/.image/[value].bin …
> NQVault Decryption (PIN + Media)

- scripts/ccl_simplesnappy.py
- scripts/ilapfuncs.py
- scripts/search_files.py
I've been profiling and testing a few changes that have a major impact on the Windows performance of ALEAPP.
The reported time goes down by about 3x on my benchmarks. The changes don't affect behavior as far as I could test, the results are consistent between runs, it just goes faster.
Mainly this is achived by placing a few caches in place (functools.lru_cache with maxsize set to None), and avoiding duplicating work (fnmatch.fnmatch usage is changed by a "deconstructed" version of it). Tried to keep the code as simple and readable as it could be, while netting some nice speedups.
There's also a small bit that covers specifically snappy decompression, where I managed to improve the algorithm just a bit. Enough to get a 4-5% performance increase, without resorting to overly complicated …
> A few optimizations

- aleappGUI.py
- plugin_loader.py
- scripts/artifacts/usagestatsVersion.py
Allows plugins to mark themselves as required or long-running (the latter currently has no impact on how they are used).
Default plugins are always selected - this has allowed us to purge the hard-coded usagestatsversion mentions as the plugin just marks itself as required.
Additional fix - users are now alerted to missing plugins in profiles
> Improved plugins

- scripts/artifacts/gmailEmails.py
Parser for emails within the Gmail app
> Gmail emails

- scripts/artifacts/browserCachechrome.py
Added mime type column and audio controls to the report
> Update Chrome Browser parser

- requirements.txt
For MacBooks with M1 Python Magic bin causes pip to crash during the installation of the dependencies, however this does not seem to affect Intel MacBooks, my solution is to add an extra check to the requirements to differentiate between different arquitecturas in the case of MacOS. (It would be interesting to see if this bug affects arm64 linux such as Raspian).
This way Intel MacBooks install the latest version of [Magic Bin](https://pypi.org/project/python-magic-bin/).
And ARM MacBooks install the latest version of [Python Magic](https://pypi.org/project/python-magic/).
> Python Magic requirments diffrent arquitecture for macos

- scripts/artifacts/GarminDailiesAPI.py
- scripts/report.py
- scripts/version_info.py
Decided to add another complementary module for the Garmin API (display the general daily data recovered from the API, the script for that is already updated in our other repo). This view is the same as the daily summaries retrieved from the private repository.
> Garmin Dailies API

- scripts/artifact_report.py
- scripts/artifacts/BadooChat.py
- scripts/artifacts/BadooConnections.py
- scripts/chat.css
- scripts/chat.js
- scripts/html_parts.py
- scripts/report.py
Create two modules for the dating app Badoo:
The **chat module** will extract all the conversations between users: (text, video, audio, images etc). The module also extracts connection information, such as name, gender, work, and all his photos.
<a href="https://ibb.co/Kh5Myq1"><img src="https://i.ibb.co/vqc7zPt/Captura-de-ecr-2023-05-03-s-20-53-17.png" alt="Captura-de-ecr-2023-05-03-s-20-53-17" border="0"></a>
To turn this into the most realistic possible, we added a new feature to ALEAPP. We present the chat window:
By clicking on the button Open chat in the datable related to the connection, the report will open the conversation that happened in a chat window format for better understanding.
This feature is purely CSS and JS and can be adapted to other applications that store …
> Add badoo modules

- README.md
- aleapp.py
- aleappGUI.py
- plugin_loader.py
> New artifact description format

- scripts/artifacts/fitbit.py
- scripts/artifacts/googleMapsGmm.py
Fixing the "locate at" field in the html report for the fitbit and googlemapsgmm artifacts.
The field was being populated with the last file_found read so it was the same everywhere even if the artifacts was from an other.
Ex : The Google Maps Label Places report was showing "Google Maps Label Places located at: z:\temp\data\data\com.google.android.apps.maps\databases\gmm_storage.db" and the artifcat came from "z:\temp\data\data\com.google.android.apps.maps\databases\gmm_myplaces.db"
>     Fixing the "locate at" field in the html report

- requirements.txt
- scripts/artifacts/AVG.py
- scripts/artifacts/appLockerfishingnet.py
- scripts/artifacts/browserCachechrome.py
- scripts/artifacts/browserCachefirefox.py
- scripts/artifacts/googlePhotos.py
- scripts/artifacts/playgroundVault.py
- scripts/filetype.py
- scripts/filetypes/__init__.py
- scripts/filetypes/application.py
- scripts/filetypes/archive.py
- scripts/filetypes/audio.py
- scripts/filetypes/base.py
- scripts/filetypes/document.py
- scripts/filetypes/font.py
- scripts/filetypes/image.py
- scripts/filetypes/isobmff.py
- scripts/filetypes/text.py
- scripts/filetypes/video.py
- scripts/ilapfuncs.py
On Apple Silicon Macs and some Windows computers, python-magic cannot run without installing additional libraries.
It was removed from requirements.txt file and is no longer needed to run ALEAPP.
filetype.py, a small and dependency free Python package to infer file type and MIME type checking the magic numbers signature of a file or buffer, has been adapted to be directly integrated into ALEAPP (easier to add new mime types).
Code was fully updated to use this new package.
> replaced the python-magic module with filetype

- aleapp.py
- aleappGUI.py
- requirements.txt
**requirements.txt:**
- remove version number for PySimpleGUI to install the latest available one
**aleappGUI.py & ALEAPP.py:**
- code updated to support the latest version of PySimpleGUI
If you want to use the latest version of PySimpleGUI, type `pip install PySimpleGUI --upgrade`
> Code updated to support the latest version of PySimpleGUI

- scripts/artifact_report.py
- scripts/artifacts/kleinanzeigen.de.py
- scripts/chat.css
- scripts/report.py
Add Message-Artifacts from messageBoxDatabase.db
Add new new_chat_window in report.py
Add Icon Data on artifact_report.py
Add new css in chat.css
Here is the Message Ovwerview
Here is an chat window
Here is the navigation
> Artifact kleinanzeigen.de

- scripts/artifacts/errp.py
- scripts/artifacts/vlcthumbsADB.py
- scripts/ilapfuncs.py
- Fixes Errp parser accounting for blank entries
- Add global function for converting local timestamp to UTC (if it includes +/-XXXX nomenclature)
> Errp Update & Global Local to UTC add

- scripts/artifacts/FCMQueuedMessagesDump.py
- scripts/artifacts/discreteNative.py
> Pirvacy dashbord update

- scripts/artifacts/kleinanzeigen.de.py
- Changed value of field "paths" in get_kleinanzeigenmessagebox -> backslashes to slashes, so the database can be found and correctly parsed.
Tested on Android 14, App Version 100.1.0
> Minor change/bug fix in kleinanzeigen.de.py

- scripts/artifacts/contacts.py
In some cases the contacts database is found in the folder pattern */com.samsung.android.providers.contacts/databases
> Contacts from com.samsung.android.providers

- scripts/artifacts/calllog.py
I found some phones where the calllog.db is on path pattern */com.samsung.android.providers.contacts/databases/calllog.db.
> Call logs from com.samsung.android.providers.contacts

- scripts/artifacts/discordChats.py
Missing asterisk = no -wal parsing.
> Bugfix: discordChats.py

- scripts/artifacts/smyfilesOpHistory.py
- scripts/artifacts/smyfilesTrash.py
Identified file paths present within Samsung My Files OperationHistory.db are encoded for particular versions - in my instance identified within Android 10, 11, 12. Through trial and error I was able to decode to meaningful information.
Additionally the Samsung My Files Trash folder structure held meaning related to a user's actions.
> Added Samsung My Files Operation History and Trash decoders

- scripts/artifacts/chromeCookies.py
Fixes missing parameter in the chromeCookies script preventing it from running successfully.
> Missing parameter from chromeCookies

- scripts/artifacts/DuckDuckGo_Bookmarks.py
- scripts/artifacts/DuckDuckGo_Favorites.py
- scripts/artifacts/DuckDuckGo_History.py
- scripts/artifacts/DuckDuckGo_OpenTabs.py
Scripts to parse DuckDuckGo Browsing History, Open Tabs, Bookmarks and Favorited Sites. Scripts have been tested on the latest app version: 5.237.0 June 3rd, 2025
LAVA compliant scripts to parse DuckDuckGo usage artifacts. Scripts have been tested on the latest app version: 5.237.0 (June 3rd, 2025), with backwards support for older versions (Slightly different database structures for Open Tabs).
Research: https://digital4n6withdamien.blogspot.com/2025/01/the-duck-hunters-guide-blog-2.html
**HTML Output**
Research: https://digital4n6withdamien.blogspot.com/2025/01/the-duck-hunters-guide-blog-3.html
**HTML Output**
Research: https://digital4n6withdamien.blogspot.com/2025/04/the-duck-hunters-guide-blog-5-bookmarks.html
**HTML Output**
Research: …
> Add DuckDuckGo Browser Parsers

- scripts/artifacts/gmailEmails.py
- LAVA support
- Fix newer version of Gmail (column for proto changed)
> Gmail Updates

- scripts/artifacts/speedtest.py
- scripts/artifacts/usagestatsVersion.py
This PR implements a plugin to extract artifacts from the Speedtest app, which contain a lot of useful data such as location data and network names. Inspired by the recently finished Belkasoft CTF :)
Test data from the CTF image: [org.zwanoo.android.speedtest.zip](https://github.com/user-attachments/files/21455127/org.zwanoo.android.speedtest.zip)
Resulting report:
> Added Speedtest artifact extractor
